version: "3.4"
services:
  pagamento-credito:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pagamentos
    ports:
      - '5432:5432'