CREATE TABLE PAGAMENTOS(
    NR_PAGAMENTO SERIAL PRIMARY KEY,
    NR_CARTAO VARCHAR(16),
    TIPO_PESSOA SMALLINT,
    NR_DOCUMENTO VARCHAR(26),
    MES_VENCIMENTO SMALLINT,
    ANO_VENCIMENTO INTEGER,
    CVV VARCHAR(4),
    DATA TIMESTAMP,
    VALOR DECIMAL
)