CREATE TABLE PAGAMENTOS(
    NR_PAGAMENTO SERIAL PRIMARY KEY,
    NR_CARTAO VARCHAR(16) NOT NULL,
    TIPO_PESSOA SMALLINT NOT NULL,
    NR_DOCUMENTO VARCHAR(26) NOT NULL,
    MES_VENCIMENTO SMALLINT NOT NULL,
    ANO_VENCIMENTO INTEGER NOT NULL,
    CVV VARCHAR(4) NOT NULL,
    DATA TIMESTAMP NOT NULL,
    VALOR DECIMAL NOT NULL
)