CREATE TABLE PAGAMENTOS(
    NR_PAGAMENTO SERIAL PRIMARY KEY,
    NR_CARTAO INTEGER NOT NULL,
    TIPO_PESSOA SMALLINT NOT NULL,
    NR_DOCUMENTO INTEGER NOT NULL,
    VENCIMENTO VARCHAR(5) NOT NULL,
    CVV VARCHAR(4) NOT NULL,
    DATA TIMESTAMP NOT NULL,
    VALOR DECIMAL NOT NULL
);